### ISSUE TITLE
Hard time implementing Refund

### ISSUE THREAD

**Issue by alex-fernandez** [CyberSource/cybersource-sdk-java#20]
Is there an example with the implementation of Refund?

**Comment by tiagoporangaba** [comment]
What kind of problem are you facing? Just implemented it, so may be I could help.

**Comment by alex-fernandez** [comment]
was there anyway to implement partial refund?

**Comment by tiagoporangaba** [comment]
Partial refund request is pretty much the same of a regular refund (Credit service), just send the partial amount you want to refund in the field purchaseTotals_grandTotalAmount.

However the important part is that the processor/acquirer you are using must be enabled and support this kind of transaction, otherwise it will fail.

**Comment by alex-fernandez** [comment]
Thanks @tiagoporangaba, Awesome!!,  we are able to implement the refund via the Credit Service. 

<?xml version="1.0" encoding="UTF-8"?><requestMessage xmlns="urn:schemas-cybersource-com:transaction-data-1.126">
    <merchantID>brandbank_au_test</merchantID>
    <merchantReferenceCode>437694</merchantReferenceCode>
    <purchaseTotals>
        <currency>AUD</currency>
        <grandTotalAmount>10.0</grandTotalAmount>
    </purchaseTotals>
    <ccCreditService run="true">
        <captureRequestID>4636277164366228701011</captureRequestID>
    </ccCreditService>
</requestMessage>
